baseURL = "https://grit0.netlify.com"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "grit"
title = "Grit Technologies Limited"
[markup.goldmark.renderer]
unsafe = false
