[[footer_left]]
name = "About Us"
url = "about-us"
[[footer_left]]
name = "Contact"
url = "contact"
[[footer_left]]
name = "Net Zero Blog"
url = "blog"
# [[footer_middle]]
# name = "Grit Bike"
# url = "http://www.gritbike.com"
[[footer_middle]]
name = "Energy Services"
url = "https://www.grit.energy"
[[footer_middle]]
name = "Education Services"
url = "https://www.unive.one"
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy"
[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"
[[footer_right]]
name = "FAQ"
url = "faq"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "Net Zero Blog"
url = "blog"
weight = 2
#[[main]]
#name = "Contact"
#url = "contact"
#weight = 4
[[main]]
name = "FAQ"
url = "faq"
weight = 5
