footer_middle = []
[[footer_left]]
name = "About Us"
url = "about-us"
[[footer_left]]
name = "Grit Energy"
url = "https://www.grit.energy"
[[footer_left]]
name = "Grit Bike"
url = "http://www.gritbike.com"
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy"
[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"
[[footer_right]]
name = "FAQ"
url = "faq"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "Blog"
url = "blog"
weight = 2
[[main]]
name = "Contact"
url = "contact"
weight = 4
[[main]]
name = "FAQ"
url = "faq"
weight = 5
