author = "Themefisher"
contact_form_action = "#"
description = "Sustainability Focused EPC" 

# favicon
favicon = "images/favicon.png"

logo = "images/logo.png"
logo_width = "200px"
social = []
[navigation_button]
enable = true
label = "Get Started"
link = "contact"
[preloader]
enable = false
preloader = ""
